// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuqwMQ_mTHVa57vZgtr7MC1qG_1dBIYKM',
    appId: '1:191915950193:web:f851a7ac4b5ba4b9c01bd0',
    messagingSenderId: '191915950193',
    projectId: 'ecoquest-a7140',
    authDomain: 'ecoquest-a7140.firebaseapp.com',
    storageBucket: 'ecoquest-a7140.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpVsv7qhMSWhBFeDizh7trTWbWDqu7wmQ',
    appId: '1:191915950193:android:be8e2c84de7555eac01bd0',
    messagingSenderId: '191915950193',
    projectId: 'ecoquest-a7140',
    storageBucket: 'ecoquest-a7140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgEgHd6ONajP7QLHFoKQ6wK2NXr381XAc',
    appId: '1:191915950193:ios:c87ebda470a01422c01bd0',
    messagingSenderId: '191915950193',
    projectId: 'ecoquest-a7140',
    storageBucket: 'ecoquest-a7140.firebasestorage.app',
    iosBundleId: 'ecoquest.com.ecoQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuqwMQ_mTHVa57vZgtr7MC1qG_1dBIYKM',
    appId: '1:191915950193:web:49bba8d212a8886bc01bd0',
    messagingSenderId: '191915950193',
    projectId: 'ecoquest-a7140',
    authDomain: 'ecoquest-a7140.firebaseapp.com',
    storageBucket: 'ecoquest-a7140.firebasestorage.app',
  );
}
