// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIolU7yoKzAVCXn3KSfjlZsYm8iQn3vM',
    appId: '1:189634070073:web:ad28beebbb564c0ddbefe8',
    messagingSenderId: '189634070073',
    projectId: 'ecoquest-ee7d4',
    authDomain: 'ecoquest-ee7d4.firebaseapp.com',
    storageBucket: 'ecoquest-ee7d4.firebasestorage.app',
    measurementId: 'G-LETDLX2R1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHjsh2_T09cZNNAmg6dq8MYql6UmnDyaA',
    appId: '1:189634070073:android:5462097247c84a74dbefe8',
    messagingSenderId: '189634070073',
    projectId: 'ecoquest-ee7d4',
    storageBucket: 'ecoquest-ee7d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_dOO8eugHR5Dz0WVBpNNJFwziqQn4yzI',
    appId: '1:189634070073:ios:8662329a446fe06cdbefe8',
    messagingSenderId: '189634070073',
    projectId: 'ecoquest-ee7d4',
    storageBucket: 'ecoquest-ee7d4.firebasestorage.app',
    iosBundleId: 'ecoquest.com.ecoQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxIolU7yoKzAVCXn3KSfjlZsYm8iQn3vM',
    appId: '1:189634070073:web:a73ab7c46df47364dbefe8',
    messagingSenderId: '189634070073',
    projectId: 'ecoquest-ee7d4',
    authDomain: 'ecoquest-ee7d4.firebaseapp.com',
    storageBucket: 'ecoquest-ee7d4.firebasestorage.app',
    measurementId: 'G-B13KWLW8V6',
  );

}